language: python
python:
  - "3.6"
  - "3.7-dev" 

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE testauthor;" -U postgres
  - psql -c "ALTER user postgres PASSWORD 'pass';" -U postgres
  - export DATABASE_URL="postgresql://postgres:pass@localhost/testauthor"
  - export SENDGRID_KEY="sengridkey"
  - export HOST_USER="username"
  - export HOST_PASSWORD="password"
  - python manage.py makemigrations
  - python manage.py migrate

services:
  - postgresql

script:
  - python manage.py test